name: Cleanup Old Runs
# 每天运行一次，或者手动点击运行
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        # 使用一个成熟的第三方插件来删除历史记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2           # 👈 这里设置保留几天（比如2天）
          keep_minimum_runs: 3     # 👈这里设置最少保留几个（防止全删光了，哪怕过了2天也留6个备查）
